import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
    output: 'server',
    adapter: cloudflare({
        platformProxy: {
            enabled: true
        }
    }),
    integrations: [],
    // Astro emits a real Content-Security-Policy *header* for SSR routes
    // (and a <meta> tag for any prerendered routes). Inline <script> blocks
    // generated by Astro are auto-hashed and added to script-src.
    // Inline on*="" attributes cannot be hashed and were refactored to
    // addEventListener.
    security: {
        csp: {
            algorithm: 'SHA-256',
            directives: [
                "default-src 'self' https:",
                "connect-src 'self' https: wss:",
                "img-src 'self' data: https:",
                "font-src 'self' data: https://fonts.gstatic.com https://fonts.googleapis.com",
                "frame-ancestors 'none'",
                "object-src 'none'",
                "base-uri 'self'",
                "require-trusted-types-for 'script'"
            ],
            styleDirective: {
                // Astro normally only allows hashed inline styles. We have
                // some unavoidable inline `style="..."` attributes so we
                // also allow 'unsafe-inline' for styles only (does not affect
                // script-src).
                resources: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com', 'https:']
            }
        }
    },
    vite: {
        ssr: {
            external: ['node:crypto']
        }
    }
});
